// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**
	 *  Filtered **and** grouped notes, ready to display. No command returns
	 *  the raw list: it would invite re-filtering on the front-end side.
	 */
	queryNotes: (query: NotesQuery) => typedError<NotesView, AppError>(__TAURI_INVOKE("query_notes", { query })),
	createNote: (draft: NoteDraft) => typedError<DisplayNote, AppError>(__TAURI_INVOKE("create_note", { draft })),
	updateNote: (id: string, patch: NotePatch) => typedError<DisplayNote, AppError>(__TAURI_INVOKE("update_note", { id, patch })),
	/**
	 *  **Met à la corbeille** : la note revient par [`restore_notes`] pendant
	 *  [`trash::RETENTION`]. Rien ne supprime définitivement sans passer par là.
	 */
	deleteNote: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("delete_note", { id })),
	/**
	 *  Renvoie le nombre de notes réellement mises à la corbeille : c'est ce que
	 *  l'annulation propose de reprendre.
	 */
	deleteNotes: (ids: string[]) => typedError<number, AppError>(__TAURI_INVOKE("delete_notes", { ids })),
	restoreNotes: (ids: string[]) => typedError<number, AppError>(__TAURI_INVOKE("restore_notes", { ids })),
	/**
	 *  Purge d'abord ce que la rétention a rattrapé : la corbeille ne doit jamais
	 *  montrer une note qu'un redémarrage effacerait.
	 */
	listTrash: () => typedError<TrashedNote[], AppError>(__TAURI_INVOKE("list_trash")),
	purgeNotes: (ids: string[]) => typedError<number, AppError>(__TAURI_INVOKE("purge_notes", { ids })),
	emptyTrash: () => typedError<number, AppError>(__TAURI_INVOKE("empty_trash")),
	moveNotes: (ids: string[], spaceId: string) => typedError<number, AppError>(__TAURI_INVOKE("move_notes", { ids, spaceId })),
	/**
	 *  Ajoute des tags à toute une sélection. Normalisés ici comme partout ailleurs,
	 *  sinon un `#urgent` saisi dans la barre d'actions ne rejoindrait pas le
	 *  `urgent` déjà en base.
	 */
	tagNotes: (ids: string[], tags: string[]) => typedError<number, AppError>(__TAURI_INVOKE("tag_notes", { ids, tags })),
	listTags: () => typedError<TagUsage[], AppError>(__TAURI_INVOKE("list_tags")),
	/**
	 *  Un renommage vers un tag déjà existant **est** une fusion : la base ne peut
	 *  pas porter deux fois le même tag sur une note.
	 */
	renameTag: (tag: string, into: string) => typedError<number, AppError>(__TAURI_INVOKE("rename_tag", { tag, into })),
	mergeTags: (tags: string[], into: string) => typedError<number, AppError>(__TAURI_INVOKE("merge_tags", { tags, into })),
	/**  Retire l'étiquette du corpus ; les notes, elles, restent. */
	deleteTag: (tag: string) => typedError<number, AppError>(__TAURI_INVOKE("delete_tag", { tag })),
	/**
	 *  Remplit les `{{champs}}` d'un contenu. Pas de base ici : la palette remplit
	 *  aussi bien un brouillon non enregistré que la note qu'elle vient d'ouvrir.
	 */
	fillPlaceholders: (content: string, values: { [key in string]: string }) => __TAURI_INVOKE<string>("fill_placeholders", { content, values }),
	/**
	 *  Enregistre les valeurs des `{{champs}}` d'une note : rouvrir la note les
	 *  retrouve, et la carte comme la palette copient avec.
	 * 
	 *  Commande à part plutôt qu'un champ de `NotePatch` : remplir un champ ne
	 *  modifie pas la note — `updated_at` reste où il est, faute de quoi le canevas
	 *  remonterait la note en tête à chaque valeur tapée.
	 */
	setPlaceholderValues: (id: string, values: { [key in string]: string }) => typedError<DisplayNote, AppError>(__TAURI_INVOKE("set_placeholder_values", { id, values })),
	listSpaces: () => typedError<Space[], AppError>(__TAURI_INVOKE("list_spaces")),
	createSpace: (draft: SpaceDraft) => typedError<Space, AppError>(__TAURI_INVOKE("create_space", { draft })),
	renameSpace: (id: string, draft: SpaceDraft) => typedError<Space, AppError>(__TAURI_INVOKE("rename_space", { id, draft })),
	/**  Transfers notes to `target_space_id` before deleting. */
	deleteSpace: (id: string, targetSpaceId: string) => typedError<null, AppError>(__TAURI_INVOKE("delete_space", { id, targetSpaceId })),
	attachFile: (noteId: string, path: string) => typedError<Attachment, AppError>(__TAURI_INVOKE("attach_file", { noteId, path })),
	/**
	 *  Attache l'image du presse-papier.
	 * 
	 *  Les octets ne traversent **pas** le pont : le presse-papier est lu côté
	 *  natif, où l'image arrive en RGBA brut, puis encodée en PNG. La faire monter
	 *  jusqu'au front pour la redescendre coûterait deux conversions et plusieurs
	 *  mégaoctets de JSON.
	 */
	attachClipboardImage: (noteId: string, fileName: string) => typedError<Attachment, AppError>(__TAURI_INVOKE("attach_clipboard_image", { noteId, fileName })),
	listAttachments: (noteId: string) => typedError<Attachment[], AppError>(__TAURI_INVOKE("list_attachments", { noteId })),
	/**
	 *  `data:<mime>;base64,…`, directement affichable dans un `<img>` ou
	 *  téléchargeable par le front.
	 */
	readAttachment: (id: string) => typedError<string, AppError>(__TAURI_INVOKE("read_attachment", { id })),
	/**
	 *  Ouvre la pièce jointe avec l'application par défaut du système.
	 * 
	 *  L'appel part du **Rust**, pas de la `WebView` : les capacités contrôlent
	 *  l'API que la `WebView` invoque, et ouvrir un chemin depuis le front aurait
	 *  demandé d'autoriser `opener:allow-open-path` sur un dossier entier.
	 */
	openAttachment: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("open_attachment", { id })),
	/**
	 *  Recopie la pièce jointe là où l'utilisateur l'a demandé. Le chemin vient d'un
	 *  sélecteur natif ; l'écriture reste ici, seul endroit qui connaît le dossier.
	 */
	saveAttachment: (id: string, path: string) => typedError<null, AppError>(__TAURI_INVOKE("save_attachment", { id, path })),
	deleteAttachment: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("delete_attachment", { id })),
	/**
	 *  Tout le corpus, ou le seul espace actif. Les espaces voyagent avec les notes :
	 *  sans eux, l'import n'aurait qu'un identifiant à ranger nulle part.
	 */
	exportNotes: (path: string, spaceId: string | null) => typedError<ExportReport, AppError>(__TAURI_INVOKE("export_notes", { path, spaceId })),
	/**
	 *  Même fichier, mêmes règles, mais restreint aux notes désignées : c'est ce
	 *  qu'on envoie à quelqu'un plutôt que toute sa bibliothèque.
	 */
	exportSelection: (path: string, ids: string[]) => typedError<ExportReport, AppError>(__TAURI_INVOKE("export_selection", { path, ids })),
	importNotes: (path: string) => typedError<ImportReport, AppError>(__TAURI_INVOKE("import_notes", { path })),
	/**
	 *  Rendu Markdown d'une sélection, que le front pose dans le presse-papier.
	 *  Rien n'est envoyé nulle part : « partager » s'arrête au presse-papier.
	 */
	shareNotes: (ids: string[]) => typedError<string, AppError>(__TAURI_INVOKE("share_notes", { ids })),
	/**
	 *  Creates the icon, or replaces only its menu if it already exists — a
	 *  language change thus re-translates it without making it flicker.
	 * 
	 *  Does **not** return a `Result`: an absent system tray is not a failure
	 *  the front end can handle, and inventing a code for it would add a branch
	 *  that nothing would display. The failure is logged on the native side, and
	 *  [`tray_exists`] then prevents closing from hiding the window where nothing
	 *  could call it back.
	 */
	syncTray: (labels: TrayLabels) => __TAURI_INVOKE<void>("sync_tray", { labels }),
	/**
	 *  Ce que le front affiche au démarrage quand un raccourci n'a pas pu être pris.
	 * 
	 *  Une liste vide est le cas courant ; elle ne produit aucun message.
	 */
	unavailableShortcuts: () => __TAURI_INVOKE<string[]>("unavailable_shortcuts"),
};

/* Types */
export type AppError = {
	code: ErrorCode,
	/**  Values to interpolate into the translated message, e.g. `{ "name": "Perso" }`. */
	params: { [key in string]: string },
	/**  Shown in the background of the banner. Not translated, but readable. */
	detail: string,
};

export type Attachment = {
	id: string,
	noteId: string,
	/**  Nom d'origine, celui qu'on affiche. Jamais utilisé comme chemin. */
	fileName: string,
	mimeType: string,
	/**
	 *  `u32` et non `u64` : Specta refuse ce que JSON ne rend pas sans perte, et
	 *  [`MAX_BYTES`] tient largement dedans.
	 */
	byteSize: number,
	createdAt: string,
};

/**
 *  One line of a todo list. No identifier: the position **is** the identity —
 *  `note_items` is keyed on `(note_id, position)` and a write rewrites the whole
 *  list, exactly like `note_tags`.
 */
export type ChecklistItem = {
	text: string,
	done: boolean,
};

/**
 *  `flatten` flattens the note into the same JSON object: the front end only has a single
 *  note type.
 */
export type DisplayNote = {
	footer: NoteFooter,
	expiringSoon: boolean,
	/**
	 *  Champs `{{…}}` du contenu, munis de ce qui a déjà été saisi pour eux :
	 *  l'éditeur les remplit, la carte propose de les remplir avant de copier.
	 *  La **liste** est dérivée du texte ; les valeurs, elles, sont persistées.
	 */
	placeholders: Placeholder[],
	/**
	 *  Renseigné après coup par ce qui dispose d'une connexion — `decorate` ne
	 *  lit pas la base. Zéro tant que personne ne l'a rempli.
	 */
	attachmentCount: number,
} & Note;

/**
 *  Adding a variant breaks the front-end build until `CODE_KEYS`
 *  (`core/errors/error-notifier.service.ts`) and both locales have their key.
 * 
 *  No "schema too recent" variant: that failure aborts startup during the
 *  migration, so no command can ever return it.
 */
export type ErrorCode = "noteNotFound" | "spaceNotFound" | "duplicateSpaceName" | "attachmentNotFound" | 
/**  Reading or writing a file outside the database failed. */
"fileAccess" | 
/**  The chosen file is not an export bundle this version can read. */
"importFormat" | 
/**  The `field` parameter names the offending field. */
"invalidInput" | 
/**  Poisoned mutex: a command panicked while holding the connection. */
"storageUnavailable" | "storage";

export type ExportReport = {
	notes: number,
	spaces: number,
};

/**
 *  `skipped` : notes déjà présentes (même identifiant) ou dont l'espace manque
 *  au fichier. Un import doit pouvoir être rejoué sans dupliquer.
 */
export type ImportReport = {
	spacesCreated: number,
	notesImported: number,
	notesSkipped: number,
};

/**
 *  **Closed** list, which is the whole point: the front end receives it as a
 *  generated TypeScript union, so an unknown value no longer compiles there
 *  instead of being refused at runtime.
 */
export type Language = "json" | "js" | "ts" | "py" | "sql" | "yml" | "toml" | "xml" | "html" | "css" | "sh" | "md" | 
/**
 *  Default, and a **signal that the front end hasn't chosen anything**:
 *  creation replaces it with a detection.
 */
"txt";

export type Note = {
	id: string,
	spaceId: string,
	/**  Can be empty: the interface then displays a translated label. */
	title: string,
	language: Language,
	content: string,
	/**  Breadcrumb, e.g. "API Gateway / Auth". Can be empty. */
	source: string,
	tags: string[],
	pinned: boolean,
	createdAt: string,
	updatedAt: string,
	lifecycle: NoteLifecycle,
	/**
	 *  ⚠️ `default` is not decoration: `transfer::Bundle` deserialises `Note`
	 *  itself, and a required key here would make every export file written
	 *  before todo-lists existed unreadable.
	 */
	kind?: NoteKind,
	/**  Empty for a snippet. A checklist has these **instead of** `content`. */
	items?: ChecklistItem[],
	/**
	 *  Ce qui a été saisi dans les `{{champs}}` du contenu, par nom de champ.
	 * 
	 *  Écrit par `set_placeholder_values` et par lui seul : remplir un champ
	 *  n'est pas modifier la note, et ne touche donc pas `updated_at`. `default`
	 *  pour la raison qui vaut déjà pour `kind` — un export écrit avant ce
	 *  champ doit rester lisible.
	 */
	placeholderValues?: { [key in string]: string },
};

/**  Neither identifier nor timestamps: persistence assigns them. */
export type NoteDraft = {
	spaceId: string,
	title: string,
	language: Language,
	content: string,
	source: string,
	tags: string[],
	pinned: boolean,
	lifecycle: NoteLifecycle,
	kind?: NoteKind,
	items?: ChecklistItem[],
};

/**  `Untriaged` = notes with a deadline, those whose fate is not decided. */
export type NoteFilter = "all" | "pinned" | "untriaged";

/**
 *  Card footer: the **decision**, not the rendering. The dated variants
 *  carry a date and not a label — "4 min ago" must age by itself
 *  on the screen, so formatting remains on the front end.
 */
export type NoteFooter = { kind: "source"; value: string } | { kind: "expiry"; at: string } | { kind: "age"; at: string };

/**
 *  **Closed** list, like `Language`: the front end receives it as a generated
 *  TypeScript union, so an unknown value stops compiling there rather than
 *  being refused at runtime.
 */
export type NoteKind = 
/**
 *  The ordinary note: a title and a coloured body. Default, and what every
 *  note written before todo-lists existed reads back as.
 */
"snippet" | 
/**  A todo list: no body, an ordered list of items instead. */
"checklist";

export type NoteLifecycle = { kind: "permanent" } | 
/**  "Untriaged" until this date. */
{ kind: "expires"; at: string };

/**
 *  A field set to `None` remains **unchanged** in the database.
 * 
 *  `#[specta(optional)]` makes keys omissible on the TypeScript side. Without it, the
 *  front end would have to send `null` for fields it doesn't touch — thus
 *  overwriting what it wanted to leave intact.
 */
export type NotePatch = {
	spaceId?: string | null,
	title?: string | null,
	language?: Language | null,
	content?: string | null,
	source?: string | null,
	tags?: string[] | null,
	pinned?: boolean | null,
	lifecycle?: NoteLifecycle | null,
	kind?: NoteKind | null,
	/**
	 *  Replaces the **whole** list, like `tags`: nothing addresses a single
	 *  item, since a position is all the identity an item has.
	 */
	items?: ChecklistItem[] | null,
};

export type NoteSection = {
	key: NoteSectionKey,
	hasExpiringNotes: boolean,
	notes: DisplayNote[],
	showCreateGhost: boolean,
};

/**
 *  **Translation key** on the front-end side (`sections.<key>`): no readable label
 *  crosses the bridge.
 */
export type NoteSectionKey = "pinned" | "today" | "week" | "older" | "results";

/**  Neither clock nor time zone read here: everything is explicit, thus reproducible in tests. */
export type NotesQuery = {
	/**
	 *  `None` = "all spaces" — a choice, not an absence of choice: there
	 *  is no "All" space on the data side.
	 */
	spaceId: string | null,
	/**  Empty = no search. */
	search: string,
	filter: NoteFilter,
	/**  A note passes if it carries **at least one** of these tags. */
	tags: string[],
	/**  Same union semantics. Empty = all. */
	languages: Language[],
	now: string,
	/**
	 *  ⚠️ `Date#getTimezoneOffset()`, whose value is the **opposite** of the offset
	 *  (UTC+2 gives −120). Sections reason in local days: at 11 PM in
	 *  Paris, `now` in UTC is already tomorrow.
	 */
	tzOffsetMinutes: number,
};

export type NotesView = {
	sections: NoteSection[],
	/**
	 *  Attached to the **space**, not the current filter: only offering facets
	 *  from already filtered notes would empty the rail upon the 1st selection.
	 */
	availableTags: string[],
	availableLanguages: Language[],
	/**  Distinguishes "no result" from "empty space". */
	isFiltering: boolean,
	/**
	 *  `u32` and not `usize`: Specta refuses to export a type the size of a
	 *  `BigInt`, which JSON does not render without loss of precision.
	 */
	matched: number,
};

export type Placeholder = {
	name: string,
	/**  Vide quand le snippet n'en propose pas. */
	defaultValue: string,
	/**
	 *  Ce que l'utilisateur a déjà saisi pour ce champ, vide s'il n'a rien
	 *  saisi. Rapporté ici plutôt que laissé dans la carte des valeurs pour
	 *  qu'une seule liste réponde à « quels champs, et où en sont-ils » — et
	 *  pour qu'une valeur devenue orpheline (le jeton a été renommé dans le
	 *  texte) reste hors de vue sans être effacée.
	 */
	value: string,
};

export type Space = {
	id: string,
	/**  Uniqueness is case-insensitive, decided by persistence. */
	name: string,
};

/**  No identifier: persistence assigns it. */
export type SpaceDraft = {
	name: string,
};

/**
 *  Un tag du corpus et le nombre de notes vivantes qui le portent : de quoi
 *  décider quoi renommer, fusionner ou jeter.
 */
export type TagUsage = {
	tag: string,
	noteCount: number,
};

/**  `flatten` : le front lit une note, avec deux dates de plus. */
export type TrashedNote = {
	deletedAt: string,
	/**
	 *  Dérivée, jamais stockée : la rétention peut changer d'une version à
	 *  l'autre et une échéance figée en base ne suivrait pas.
	 */
	purgeAt: string,
} & Note;

/**
 *  Labels cross the bridge **already translated**: the interface language
 *  is a front-end preference, and keeping a translation table in Rust would
 *  mean maintaining a second one.
 */
export type TrayLabels = {
	open: string,
	newNote: string,
	capture: string,
	palette: string,
	quit: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

