// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**
	 *  Notes filtrées **et** regroupées, prêtes à afficher. Aucune commande ne rend
	 *  la liste brute : elle inviterait à refiltrer côté front.
	 */
	queryNotes: (query: NotesQuery) => typedError<NotesView, AppError>(__TAURI_INVOKE("query_notes", { query })),
	createNote: (draft: NoteDraft) => typedError<DisplayNote, AppError>(__TAURI_INVOKE("create_note", { draft })),
	updateNote: (id: string, patch: NotePatch) => typedError<DisplayNote, AppError>(__TAURI_INVOKE("update_note", { id, patch })),
	deleteNote: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("delete_note", { id })),
	listSpaces: () => typedError<Space[], AppError>(__TAURI_INVOKE("list_spaces")),
	createSpace: (draft: SpaceDraft) => typedError<Space, AppError>(__TAURI_INVOKE("create_space", { draft })),
	renameSpace: (id: string, draft: SpaceDraft) => typedError<Space, AppError>(__TAURI_INVOKE("rename_space", { id, draft })),
	/**  Transfère les notes vers `target_space_id` avant de supprimer. */
	deleteSpace: (id: string, targetSpaceId: string) => typedError<null, AppError>(__TAURI_INVOKE("delete_space", { id, targetSpaceId })),
	/**
	 *  Ne renvoie **pas** de `Result` : une barre système absente n'est pas une panne
	 *  que le front puisse traiter, et lui inventer un code ajouterait une branche
	 *  que rien n'afficherait. L'échec est journalisé côté natif.
	 */
	syncTray: (labels: TrayLabels) => __TAURI_INVOKE<void>("sync_tray", { labels }),
};

/* Types */
export type AppError = {
	code: ErrorCode,
	/**  Valeurs à interpoler dans le message traduit, ex. `{ "name": "Perso" }`. */
	params: { [key in string]: string },
	/**  Affiché en second plan de la bannière. Pas traduit, mais lisible. */
	detail: string,
};

/**
 *  `flatten` aplatit la note dans le même objet JSON : le front n'a qu'un seul
 *  type de note.
 */
export type DisplayNote = {
	footer: NoteFooter,
	expiringSoon: boolean,
} & Note;

/**
 *  Ajouter une variante casse la compilation du front tant que `CODE_KEYS`
 *  (`core/errors/error-notifier.service.ts`) et les deux locales n'ont pas leur
 *  clé.
 * 
 *  Pas de variante « schéma trop récent » : cette panne avorte le lancement
 *  pendant la migration, aucune commande ne peut la renvoyer.
 */
export type ErrorCode = "noteNotFound" | "spaceNotFound" | "duplicateSpaceName" | 
/**  Le paramètre `field` nomme le champ en cause. */
"invalidInput" | 
/**  Mutex empoisonné : une commande a paniqué en tenant la connexion. */
"storageUnavailable" | "storage";

/**
 *  Liste **fermée**, et c'est tout l'intérêt : le front la reçoit en union
 *  TypeScript générée, donc une valeur inconnue ne compile plus chez lui au lieu
 *  d'être refusée à l'exécution.
 */
export type Language = "json" | "js" | "ts" | "py" | "sql" | "yml" | "toml" | "xml" | "html" | "css" | "sh" | "md" | 
/**
 *  Défaut, et **signal que le front n'a rien choisi** : c'est lui que la
 *  création remplace par une détection.
 */
"txt";

export type Note = {
	id: string,
	spaceId: string,
	/**  Peut être vide : l'interface affiche alors un libellé traduit. */
	title: string,
	language: Language,
	content: string,
	/**  Fil d'Ariane libre, ex. "API Gateway / Auth". Peut être vide. */
	source: string,
	tags: string[],
	pinned: boolean,
	createdAt: string,
	updatedAt: string,
	lifecycle: NoteLifecycle,
};

/**  Ni identifiant ni horodatages : la persistance les attribue. */
export type NoteDraft = {
	spaceId: string,
	title: string,
	language: Language,
	content: string,
	source: string,
	tags: string[],
	pinned: boolean,
	lifecycle: NoteLifecycle,
};

/**  `Untriaged` = notes portant une échéance, celles dont le sort n'est pas décidé. */
export type NoteFilter = "all" | "pinned" | "untriaged";

/**
 *  Pied d'une carte : la **décision**, pas le rendu. Les variantes datées
 *  portent une date et non un libellé — « il y a 4 min » doit vieillir tout seul
 *  à l'écran, donc le formatage reste au front.
 */
export type NoteFooter = { kind: "source"; value: string } | { kind: "expiry"; at: string } | { kind: "age"; at: string };

export type NoteLifecycle = { kind: "permanent" } | 
/**  « À trier » jusqu'à cette date. */
{ kind: "expires"; at: string };

/**
 *  Un champ à `None` reste **inchangé** en base.
 * 
 *  `#[specta(optional)]` rend les clés omissibles côté TypeScript. Sans lui le
 *  front devrait envoyer des `null` pour les champs qu'il ne touche pas — donc
 *  écraser ce qu'il voulait laisser intact.
 */
export type NotePatch = {
	spaceId?: string | null,
	title?: string | null,
	language?: Language | null,
	content?: string | null,
	source?: string | null,
	tags?: string[] | null,
	pinned?: boolean | null,
	lifecycle?: NoteLifecycle | null,
};

export type NoteSection = {
	key: NoteSectionKey,
	hasExpiringNotes: boolean,
	notes: DisplayNote[],
	showCreateGhost: boolean,
};

/**
 *  **Clé de traduction** côté front (`sections.<key>`) : aucun libellé lisible
 *  ne traverse le pont.
 */
export type NoteSectionKey = "pinned" | "today" | "week" | "older" | "results";

/**  Ni horloge ni fuseau lus ici : tout est explicite, donc reproductible en test. */
export type NotesQuery = {
	/**
	 *  `None` = « tous les espaces » — un choix, pas une absence de choix : il
	 *  n'existe aucun espace « Tous » côté données.
	 */
	spaceId: string | null,
	/**  Vide = pas de recherche. */
	search: string,
	filter: NoteFilter,
	/**  Une note passe si elle porte **au moins un** de ces tags. */
	tags: string[],
	/**  Même sémantique d'union. Vide = tous. */
	languages: Language[],
	now: string,
	/**
	 *  ⚠️ `Date#getTimezoneOffset()`, dont la valeur est l'**opposé** du décalage
	 *  (UTC+2 donne −120). Les sections raisonnent en jours locaux : à 23 h à
	 *  Paris, `now` en UTC est déjà demain.
	 */
	tzOffsetMinutes: number,
};

export type NotesView = {
	sections: NoteSection[],
	/**
	 *  Portées à l'**espace**, pas au filtre courant : n'offrir que les facettes
	 *  des notes déjà filtrées viderait le rail dès la 1re sélection.
	 */
	availableTags: string[],
	availableLanguages: Language[],
	/**  Distingue « aucun résultat » d'« espace vide ». */
	isFiltering: boolean,
	/**
	 *  `u32` et non `usize` : Specta refuse d'exporter un type de la taille d'un
	 *  `BigInt`, que JSON ne rend pas sans perte de précision.
	 */
	matched: number,
};

export type Space = {
	id: string,
	/**  Unicité insensible à la casse, tranchée par la persistance. */
	name: string,
};

/**  Pas d'identifiant : la persistance l'attribue. */
export type SpaceDraft = {
	name: string,
};

export type TrayLabels = {
	open: string,
	newNote: string,
	capture: string,
	quit: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

