// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  No command returns the raw list: it would invite re-filtering on the front end. */
	queryNotes: (query: NotesQuery) => typedError<NotesView, AppError>(__TAURI_INVOKE("query_notes", { query })),
	createNote: (draft: NoteDraft) => typedError<DisplayNote, AppError>(__TAURI_INVOKE("create_note", { draft })),
	updateNote: (id: string, patch: NotePatch) => typedError<DisplayNote, AppError>(__TAURI_INVOKE("update_note", { id, patch })),
	/**
	 *  **Moves to the trash**: the note comes back through [`restore_notes`] for
	 *  [`trash::RETENTION`].
	 */
	deleteNote: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("delete_note", { id })),
	deleteNotes: (ids: string[]) => typedError<number, AppError>(__TAURI_INVOKE("delete_notes", { ids })),
	restoreNotes: (ids: string[]) => typedError<number, AppError>(__TAURI_INVOKE("restore_notes", { ids })),
	/**
	 *  Purges what retention has caught up with **first**: the trash must never
	 *  show a note a restart would erase.
	 */
	listTrash: () => typedError<TrashedNote[], AppError>(__TAURI_INVOKE("list_trash")),
	purgeNotes: (ids: string[]) => typedError<number, AppError>(__TAURI_INVOKE("purge_notes", { ids })),
	emptyTrash: () => typedError<number, AppError>(__TAURI_INVOKE("empty_trash")),
	moveNotes: (ids: string[], spaceId: string) => typedError<number, AppError>(__TAURI_INVOKE("move_notes", { ids, spaceId })),
	/**
	 *  Normalized here as everywhere else, or an `#urgent` typed in the action bar
	 *  would not join the `urgent` already stored.
	 */
	tagNotes: (ids: string[], tags: string[]) => typedError<number, AppError>(__TAURI_INVOKE("tag_notes", { ids, tags })),
	listTags: () => typedError<TagUsage[], AppError>(__TAURI_INVOKE("list_tags")),
	/**  Renaming onto an existing tag **is** a merge: a note cannot carry one twice. */
	renameTag: (tag: string, into: string) => typedError<number, AppError>(__TAURI_INVOKE("rename_tag", { tag, into })),
	mergeTags: (tags: string[], into: string) => typedError<number, AppError>(__TAURI_INVOKE("merge_tags", { tags, into })),
	/**
	 *  A list rather than one tag at a time: the panel deletes a whole selection, and
	 *  one round trip per tag was one lock and one transaction per tag.
	 */
	deleteTags: (tags: string[]) => typedError<number, AppError>(__TAURI_INVOKE("delete_tags", { tags })),
	/**
	 *  No note identifier: the palette fills an unsaved draft as readily as the note
	 *  it just opened. The database is read only for the **global variables**.
	 */
	fillPlaceholders: (content: string, values: { [key in string]: string }) => typedError<string, AppError>(__TAURI_INVOKE("fill_placeholders", { content, values })),
	/**
	 *  ⚠️ A command of its own rather than a `NotePatch` field: filling a field is not
	 *  editing the note, so `updated_at` stays put — the canvas sorts on it.
	 */
	setPlaceholderValues: (id: string, values: { [key in string]: string }) => typedError<DisplayNote, AppError>(__TAURI_INVOKE("set_placeholder_values", { id, values })),
	listGlobalPlaceholders: () => typedError<{ [key in string]: string }, AppError>(__TAURI_INVOKE("list_global_placeholders")),
	/**
	 *  Stores the **whole** set: what is not sent is what the user removed. No note is
	 *  touched, not even its `updated_at`.
	 */
	setGlobalPlaceholders: (values: { [key in string]: string }) => typedError<{ [key in string]: string }, AppError>(__TAURI_INVOKE("set_global_placeholders", { values })),
	listSpaces: () => typedError<Space[], AppError>(__TAURI_INVOKE("list_spaces")),
	createSpace: (draft: SpaceDraft) => typedError<Space, AppError>(__TAURI_INVOKE("create_space", { draft })),
	renameSpace: (id: string, draft: SpaceDraft) => typedError<Space, AppError>(__TAURI_INVOKE("rename_space", { id, draft })),
	/**  Hoists a space to the head of the list, or lets it fall back among the others. */
	pinSpace: (id: string, pinned: boolean) => typedError<Space, AppError>(__TAURI_INVOKE("pin_space", { id, pinned })),
	deleteSpace: (id: string, targetSpaceId: string) => typedError<null, AppError>(__TAURI_INVOKE("delete_space", { id, targetSpaceId })),
	attachFile: (noteId: string, path: string) => typedError<Attachment, AppError>(__TAURI_INVOKE("attach_file", { noteId, path })),
	/**
	 *  The bytes do **not** cross the bridge: the clipboard is read natively, where the
	 *  image arrives as raw RGBA, then encoded to PNG.
	 */
	attachClipboardImage: (noteId: string, fileName: string) => typedError<Attachment, AppError>(__TAURI_INVOKE("attach_clipboard_image", { noteId, fileName })),
	listAttachments: (noteId: string) => typedError<Attachment[], AppError>(__TAURI_INVOKE("list_attachments", { noteId })),
	readAttachment: (id: string) => typedError<string, AppError>(__TAURI_INVOKE("read_attachment", { id })),
	/**
	 *  The call starts from **Rust**, not the `WebView`: opening a path from the front
	 *  end would have meant allowing `opener:allow-open-path` over a whole directory.
	 */
	openAttachment: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("open_attachment", { id })),
	/**
	 *  The path comes from a native picker; the write stays here, the only place that
	 *  knows the directory.
	 */
	saveAttachment: (id: string, path: string) => typedError<null, AppError>(__TAURI_INVOKE("save_attachment", { id, path })),
	deleteAttachment: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("delete_attachment", { id })),
	/**
	 *  The spaces travel with the notes: without them an import would hold an id with
	 *  nowhere to file it.
	 */
	exportNotes: (path: string, spaceId: string | null) => typedError<ExportReport, AppError>(__TAURI_INVOKE("export_notes", { path, spaceId })),
	exportSelection: (path: string, ids: string[]) => typedError<ExportReport, AppError>(__TAURI_INVOKE("export_selection", { path, ids })),
	/**
	 *  The file is read **before** the lock is taken: parsing a large export while
	 *  holding the connection would block every other command for the length of it.
	 */
	importNotes: (path: string) => typedError<ImportReport, AppError>(__TAURI_INVOKE("import_notes", { path })),
	/**  Nothing is sent anywhere: "share" stops at the clipboard. */
	shareNotes: (ids: string[]) => typedError<string, AppError>(__TAURI_INVOKE("share_notes", { ids })),
	appChangelog: () => __TAURI_INVOKE<ChangelogRelease[]>("app_changelog"),
	/**
	 *  Replaces only the menu when the tray already exists, so a language change does
	 *  not make it flicker.
	 * 
	 *  No `Result`: an absent tray is not a failure the front end can handle, and
	 *  [`tray_exists`] is what then keeps closing from hiding the window where nothing
	 *  could call it back.
	 */
	syncTray: (labels: TrayLabels) => __TAURI_INVOKE<void>("sync_tray", { labels }),
	/**
	 *  Returns the ones another application keeps: the native side can only fail
	 *  silently, and a log line is not an interface — the front end displays this.
	 */
	setGlobalShortcuts: (bindings: ShortcutBindings) => __TAURI_INVOKE<string[]>("set_global_shortcuts", { bindings }),
	setWindowBehavior: (behavior: WindowBehavior) => __TAURI_INVOKE<void>("set_window_behavior", { behavior }),
};

/* Constants */
export const APP_METADATA = {"author":"Valentin MILLET","authorHandle":"@vmillet-dev","name":"DevBox","repository":"https://github.com/vmillet-dev/devbox-rs","rustVersion":"1.97.1"} as const;

export const GLOBAL_ACTION_EVENT = "devbox:action" as const;

/* Types */
export type AppError = {
	code: ErrorCode,
	/**  Values to interpolate into the translated message, e.g. `{ "name": "Personal" }`. */
	params: { [key in string]: string },
	detail: string,
};

export type Attachment = {
	id: string,
	noteId: string,
	/**  The original name, the one displayed. Never used as a path. */
	fileName: string,
	mimeType: string,
	/**  `u32` and not `u64`: Specta refuses what JSON cannot carry without loss. */
	byteSize: number,
	createdAt: string,
};

export type ChangelogRelease = {
	/**
	 *  `0.1.1`, or whatever the heading names — `Unreleased` included. Keep a
	 *  Changelog's square brackets are dropped.
	 */
	version: string,
	/**  `None` when the heading carries no date; never invented. */
	date: string | null,
	sections: ChangelogSection[],
};

/**
 *  One `### ` heading, or the anonymous one a release gets when it lists its entries
 *  without a category.
 */
export type ChangelogSection = {
	/**  Empty for that anonymous category: the front then renders no heading. */
	title: string,
	items: string[],
};

/**
 *  No identifier: the position **is** the identity — `note_items` is keyed on
 *  `(note_id, position)`, and a write rewrites the whole list.
 */
export type ChecklistItem = {
	text: string,
	done: boolean,
};

/**  `flatten`: the front end has a single note type. */
export type DisplayNote = {
	footer: NoteFooter,
	expiringSoon: boolean,
	/**  The **list** is derived from the text; the values are persisted. */
	placeholders: Placeholder[],
	/**  Filled in afterwards by whoever holds a connection: `decorate` reads no database. */
	attachmentCount: number,
	/**
	 *  What copying puts on the clipboard when that is **not** the content: a todo
	 *  list travels as the Markdown of its items, a snippet as `None`. Decided here
	 *  so `checklist::to_markdown` stays the only place the `- [x] ` syntax exists.
	 */
	copyText: string | null,
	/**
	 *  Why this note is in the results, when the card is not already showing it.
	 *  Filled in afterwards by `view::build`, like the attachment count above it —
	 *  `None` outside a search, and for a note found by its own title.
	 */
	searchHit: SearchHit | null,
} & Note;

/**
 *  Adding a variant breaks the front-end build until `CODE_KEYS`
 *  (`core/errors/error-notifier.service.ts`) and both locales have their key.
 * 
 *  No "schema too recent" variant: that failure aborts startup during the
 *  migration, so no command can ever return it.
 */
export type ErrorCode = "noteNotFound" | "spaceNotFound" | "duplicateSpaceName" | "attachmentNotFound" | "fileAccess" | "importFormat" | 
/**  The `field` parameter names the offending field. */
"invalidInput" | 
/**  Poisoned mutex: a command panicked while holding the connection. */
"storageUnavailable" | "storage";

export type ExportReport = {
	notes: number,
	spaces: number,
};

/**
 *  **One** event carrying a closed value, not one topic per action: the topic
 *  strings used to be mirrored in `app-events.service.ts`, where a typo made a
 *  subscription silently inert. It crosses as a generated TypeScript union, so
 *  a variant added here stops the front end compiling until its `switch` handles it.
 */
export type GlobalAction = 
/**  The clipboard, as a note. */
"capture" | "new-note" | "palette";

/**
 *  `skipped`: notes already present (same id) or whose space is missing from the
 *  file — an import has to be replayable without duplicating.
 */
export type ImportReport = {
	spacesCreated: number,
	notesImported: number,
	notesSkipped: number,
	/**
	 *  Imported, but with a `language` or a `kind` this build does not know brought
	 *  down to the default. Counted so the loss is said rather than discovered.
	 */
	notesDegraded: number,
};

/**
 *  **Closed**: the front end receives it as a generated TypeScript union, so
 *  an unknown value stops compiling there instead of being refused at runtime.
 */
export type Language = "json" | "js" | "ts" | "py" | "rs" | "go" | "java" | "cs" | "php" | "c" | "sql" | "yml" | "toml" | "xml" | "html" | "css" | "sh" | "md" | 
/**  Default, and the signal that the front end chose nothing. */
"txt";

export type Note = {
	id: string,
	spaceId: string,
	title: string,
	language: Language,
	content: string,
	/**  Breadcrumb, e.g. "API Gateway / Auth". Can be empty. */
	source: string,
	tags: string[],
	pinned: boolean,
	createdAt: string,
	updatedAt: string,
	lifecycle: NoteLifecycle,
	/**
	 *  ⚠️ `default`: `transfer::Bundle` deserializes `Note` itself, and a required
	 *  key would make every export file written before todo-lists unreadable.
	 */
	kind?: NoteKind,
	/**  Empty for a snippet. A checklist has these **instead of** `content`. */
	items?: ChecklistItem[],
	/**
	 *  Written by `set_placeholder_values` and by nothing else: filling a field is
	 *  not editing the note, so it leaves `updated_at` alone.
	 */
	placeholderValues?: { [key in string]: string },
};

export type NoteDraft = {
	spaceId: string,
	title: string,
	language: Language,
	content: string,
	source: string,
	tags: string[],
	pinned: boolean,
	lifecycle: NoteLifecycle,
	kind?: NoteKind,
	items?: ChecklistItem[],
};

/**  `Untriaged` = notes with a deadline, those whose fate is not decided. */
export type NoteFilter = "all" | "pinned" | "untriaged";

/**
 *  The **decision**, not the rendering: the dated variants carry a date and not a
 *  label — "4 min ago" has to age on screen without a round trip.
 */
export type NoteFooter = { kind: "source"; value: string } | { kind: "expiry"; at: string } | { kind: "age"; at: string };

/**
 *  **Closed**, like `Language`: the front end receives it as a generated
 *  TypeScript union, so an unknown value stops compiling there.
 */
export type NoteKind = 
/**  Default, and what every note written before todo-lists reads back as. */
"snippet" | 
/**  A todo list: no body, an ordered list of items instead. */
"checklist";

export type NoteLifecycle = { kind: "permanent" } | 
/**  "Untriaged" until this date. */
{ kind: "expires"; at: string };

/**
 *  A field set to `None` stays **unchanged**. `#[specta(optional)]` makes the key
 *  omissible on the TypeScript side; without it the front would send `null` for
 *  what it does not touch, overwriting it.
 */
export type NotePatch = {
	spaceId?: string | null,
	title?: string | null,
	language?: Language | null,
	content?: string | null,
	source?: string | null,
	tags?: string[] | null,
	pinned?: boolean | null,
	lifecycle?: NoteLifecycle | null,
	kind?: NoteKind | null,
	/**
	 *  Replaces the **whole** list, like `tags`: a position is all the identity an
	 *  item has.
	 */
	items?: ChecklistItem[] | null,
};

export type NoteSection = {
	key: NoteSectionKey,
	hasExpiringNotes: boolean,
	notes: DisplayNote[],
	showCreateGhost: boolean,
};

/**
 *  **Translation key** on the front-end side (`sections.<key>`): no readable label
 *  crosses the bridge.
 */
export type NoteSectionKey = "pinned" | "today" | "week" | "older" | "results";

export type NotesQuery = {
	/**  `None` = every space: a choice, not an absence of one. */
	spaceId: string | null,
	search: string,
	filter: NoteFilter,
	/**  A note passes if it carries **at least one** of these tags. */
	tags: string[],
	languages: Language[],
	now: string,
	/**
	 *  ⚠️ `Date#getTimezoneOffset()`, whose sign is the **opposite** of the offset
	 *  (−120 for UTC+2). Sections reason in local days.
	 */
	tzOffsetMinutes: number,
	/**
	 *  Hoists pinned notes: their own section when the view is chronological, the
	 *  head of the list when it is flat. The canvas always says `true`.
	 */
	pinnedFirst: boolean,
};

export type NotesView = {
	sections: NoteSection[],
	/**
	 *  Attached to the **space**, not the current filter: facets drawn from
	 *  already filtered notes would empty the rail on the first selection.
	 */
	availableTags: string[],
	availableLanguages: Language[],
	/**  Distinguishes "no result" from "empty space". */
	isFiltering: boolean,
	/**  `u32` and not `usize`: Specta refuses a type JSON cannot render losslessly. */
	matched: number,
};

export type Placeholder = {
	name: string,
	defaultValue: string,
	/**
	 *  A value gone orphan — its token renamed in the text — stays out of sight
	 *  here without being erased.
	 */
	value: string,
};

/**
 *  Which part of a note a search found, when the card is not already showing it.
 * 
 *  ⚠️ No `Title` variant, deliberately: the title is the biggest thing on a card, so a
 *  note found by it needs no explanation and an excerpt would repeat what the reader is
 *  looking at. "Matched on the title" is [`SearchMatch::Title`], which carries nothing.
 */
export type SearchField = "tag" | "body" | "item";

/**
 *  What made a note match, and where — so a card can show the line that put it in the
 *  results rather than its first three, which may have nothing to do with the query.
 */
export type SearchHit = {
	field: SearchField,
	/**  The matching **line**, not the whole body: a card has room for one. */
	excerpt: string,
};

/**
 *  Three fields rather than a map: a missing shortcut would be an action no key
 *  reaches any more, and a map would leave the compiler silent about it.
 */
export type ShortcutBindings = {
	capture: string,
	newNote: string,
	palette: string,
};

export type Space = {
	id: string,
	/**  Uniqueness is case-insensitive, decided by persistence. */
	name: string,
	/**  Hoisted to the head of the list, the way a pinned note is on the canvas. */
	pinned?: boolean,
};

export type SpaceDraft = {
	name: string,
};

export type TagUsage = {
	tag: string,
	noteCount: number,
};

export type TrashedNote = {
	deletedAt: string,
	/**  Derived, never stored: retention can change between versions. */
	purgeAt: string,
} & Note;

/**
 *  Labels cross the bridge **already translated**: the interface language is a
 *  front-end preference, and a translation table in Rust would be a second one.
 */
export type TrayLabels = {
	open: string,
	newNote: string,
	capture: string,
	palette: string,
	quit: string,
};

/**
 *  Set from the preferences panel and pushed here, like the tray labels: the
 *  preference lives in `preferences.json`, and reading it back from Rust would be
 *  a second source to keep in step.
 */
export type WindowBehavior = {
	closeToTray: boolean,
	minimizeToTray: boolean,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

